source 'https://rubygems.org'

#Core Gems 
gem 'rails', '4.1.8'
gem 'sqlite3'

#Front End Section
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'simple_form'
gem 'font-awesome-sass'

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
#gem 'spring',        group: :development

#Debugging Tools 
group :development do
  gem 'annotate'
  gem 'thin' #better server 
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'byebug'
  gem 'pry'
end

#Doc Stuff
gem 'sdoc', '~> 0.4.0',          group: :doc


