source 'https://rubygems.org'

#Core Management
gem 'rails', '4.2.0'
gem 'sqlite3'

#Front End Management
gem 'sass-rails'
gem 'bootstrap-sass' #add this 
gem 'autoprefixer-rails', '4.0.0' #add this 
gem 'simple_form' #add this 
gem 'font-awesome-sass', '~> 4.2.0'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'

#Testing & Debugging Tools 
group :development do
  gem 'annotate'
  gem 'pry-rails'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'pry'
  gem 'pry-byebug'
  gem 'thin'
  gem 'spring'
end

